
CREATE TABLE Disks
(
	DiskId		INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	Label		CHAR(10)
);
 
INSERT INTO Disks(Label) VALUES ("CD_Cache");

CREATE TABLE Songs
(
	SongId		INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	Artist		CHAR(60),
	Title		CHAR(60) NOT NULL,
	Album		CHAR(60),
	Genre		CHAR(20),
	Length		INTEGER NOT NULL,
	BitRate		INTEGER,
	Rating		INTEGER DEFAULT 0,
	Year		INTEGER,
	DiskId		INTEGER NOT NULL DEFAULT 1 REFERENCES Disks(DiskId),
	FileSize	INTEGER NOT NULL,
	FileName	CHAR(255) NOT NULL
);

